### ISSUE TITLE
Including specific documents in the list of sources

### ISSUE THREAD

**Issue by Florin196** [stanford-oval/storm#101]
Hello,

I am writing to ask if it is possible to include specific documents (e.g., pdf) and/or specific webpages in the list of sources to be consulted by STORM. If yes, then how it can be done?

Thanks,
Florin

**Comment by shaoyijia** [comment]
Currently, STORM supports retrieving information with `VectorRM`. So one way to do this is preprocessing your specific documents and websites into the format that can be handled by `VectorRM`.

If you need more flexibility/control on the retrieving part, you could define your own retrieval instance following examples in [rm.py](https://github.com/stanford-oval/storm/blob/main/knowledge_storm/rm.py).

**Comment by Yucheng-Jiang** [comment]
Will close the issue if no further question on this thread.
