### ISSUE TITLE
Support gemini!

### ISSUE THREAD

**Issue by amrpyt** [stanford-oval/storm#103]
**Is there any future update on supporting Gemini?**

**Comment by shaoyijia** [comment]
Yeah, happy to support. Previously, I don't have enough credit to test it.

**Comment by amrpyt** [comment]
> Yeah, happy to support. Previously, I don't have enough credit to test it.

I think it will be great because they have a free API rates.

**Comment by shaoyijia** [comment]
Hi @amrpyt , I add support for Gemini models and provide a script to run it end to end (see #105). Are you willing to give it a test? Based on my initial test with "2024 Paris Olympics Opening Ceremony", the script can run successfully, but the output quality is much lower than other models we currently support.

I haven't used Gemini models before, so would appreciate feedback on whether my current support is correct.

**Comment by Yucheng-Jiang** [comment]
close as #128 merged.
