### ISSUE TITLE
Export Research to document (PDF, DOCX)

### ISSUE THREAD

**Issue by MrEdwards007** [stanford-oval/storm#106]
I see that within the  page on https://storm.genie.stanford.edu/ there is an option to show an article as a PDF.
Will that capability become part of the source, which can be run locally, either as PDF or DOCX?

**Comment by Yucheng-Jiang** [comment]
That would be a great feature to include in the demo_light! Our team right now are prioritizing effort on tasks described in [road map section of readme](https://github.com/stanford-oval/storm#roadmap--contributions). We are happy to review and merge effort on improving demo light.

**Comment by MyraBaba** [comment]
waiting to pdf export as in product demo page..
