### ISSUE TITLE
where to find the code of Replicate NAACL2024 result

### ISSUE THREAD

**Issue by verigle** [stanford-oval/storm#109]
> For batch experiment on FreshWiki dataset:
> ```shell
> python -m scripts.run_prewriting --input-source file --input-path ../FreshWiki/topic_list.csv  --engine gpt-4 --do-research --max-conv-turn 5 --max-perspective 5
> ```
> 
> ```shell
> python -m scripts.run_writing --input-source console --engine gpt-4 --do-polish-article --remove-duplicate
> ```

where to find those code ?

**Comment by Yucheng-Jiang** [comment]
Please follow instructions under this section in readme: https://github.com/stanford-oval/storm?tab=readme-ov-file#replicate-naacl2024-result. You would need to switch branch.

**Comment by Yucheng-Jiang** [comment]
Will close this issue if there's no further question on this thread by EOD today.
