### ISSUE TITLE
How many iterations of questions will it ask?

### ISSUE THREAD

**Issue by ferrygun** [stanford-oval/storm#110]
I am wondering where the setting which simulates a conversation between a Wikipedia writer with a specific persona and an expert ? How many iterations of questions will it ask ? Where is that setting in the code?

_In practice, we limit the conversation to at most M rounds_

Is this the one?
max_conv_turn: int = field(
        default=3,
        metadata={"help": "Maximum number of questions in conversational question asking."},
    )

**Comment by shaoyijia** [comment]
Your understanding is correct.

We control the `STORMWikiRunner` with [`STORMWikiRunnerArguments`](https://github.com/stanford-oval/storm/blob/main/knowledge_storm/storm_wiki/engine.py#L86). You can find more information there.

**Comment by ferrygun** [comment]
Thank you, another question, how does the relevant question is generated as I am unfamiliar with dspy?

**Comment by Yucheng-Jiang** [comment]
Could you clarify on "relevant question"? Do you mean how the question is generated for perspective guided QA?

**Comment by ferrygun** [comment]
Thats correct, is it defined in dspy.dsp.HFModel?

**Comment by Yucheng-Jiang** [comment]
@ferrygun It is defined by `max_conv_turn` in [STORMWikiRunnerArguments](https://github.com/stanford-oval/storm/blob/6a57b0ce963f1e2aa649418b5a66e2a806d365a6/knowledge_storm/storm_wiki/engine.py#L91). Each conv turn contains one question been asked by "Wiki writer" role and one corresponding answer by "expert" role.
