### ISSUE TITLE
Local Corpus - Reference Not Inserted 

### ISSUE THREAD

**Issue by Justinius** [stanford-oval/storm#117]
I modified the run_storm_wiki_with_gpt_with_VectorRM.py file to use a local install of Ollama on a set of local documents using the Arxiv dataset.  I was using LLama3.1 8b as the local model to just see how it worked.

It generated the document but there references were not populated - is that expected?
**References:
[1] [Insert reference to study using VSD]
[2] [Insert reference to study using VML]
Note: The references are placeholders and should be replaced with actual citations to relevant studies.**

I guess I assumed they were autogenerated in the process - any feedback on what I may be missing in the work flow?

**Comment by Yucheng-Jiang** [comment]
You would see a file named after `url_to_info.json` in the output directory, in which there is a field called `url_to_unified_index`. From there you can map the index to the actual uuid of the file.

**Comment by Justinius** [comment]
Thanks for the feedback - that can be added then as a post processing step.  As I was looking at the result it actually found 3 items in 3 documents to reference, but it only generated two reference lines - again not a huge issue, but something I noticed.

**Comment by Yucheng-Jiang** [comment]
@Justinius Thanks for reporting. In the article generation stage, we enforce the LLM not to generate a reference section ([code reference here](https://github.com/stanford-oval/storm/blob/6a57b0ce963f1e2aa649418b5a66e2a806d365a6/knowledge_storm/utils.py#L205)). I'm not sure if the reference section above you shared is automatic generated from language model or not. 

In our [STORM online UI](http://storm.genie.stanford.edu), the reference section of PDF is rendered as a post processing step.
