### ISSUE TITLE
Unable to run streamlit frontend

### ISSUE THREAD

**Issue by danieldekay** [stanford-oval/storm#120]
I am just trying to run the streamlit frontend into a fresh python environment.

`pip install -r requirements.txt` 
succeeds.

**But**: 
`pip install knowledge_storm` 
fails:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.31.1 requires protobuf<5,>=3.20, but you have protobuf 5.27.3 which is incompatible.`

**Comment by Yucheng-Jiang** [comment]
@danieldekay Thanks for reporting. We'll look into this. Meanwhile, this should be a warning and I think you can still run the environment and spin up the frontend successfully.

**Comment by danieldekay** [comment]
Unfortunately, no. I can't install the knowledge_storm package, and then streamlit won't run.

**Comment by Yucheng-Jiang** [comment]
Just to clarify, `pip install -r requirements.txt` is for requirements.txt file at repo root or demo_light root?

**Comment by danieldekay** [comment]
I create a new environment for the streamlit app, where I am installing it's `requirements.txt`, and then also `knowledge_storm` via `pip install knowledge_storm,` as it is missing.

The repo root app runs well. But even there, I can't install the streamlit app's `requirements.txt`

**Comment by Yucheng-Jiang** [comment]
```bash
conda create -n storm python=3.11
conda activate storm
pip install knowledge-storm
pip install -r <repo_root>/frontend/demo_light/requirements.txt
```
I can make streamlit running with these steps, though with the protobuf version error.

**Comment by danieldekay** [comment]
will try tomorrow, and let you know.

**Comment by Yucheng-Jiang** [comment]
sure thing. We'll update the dependency to resolve this issue shortly.

**Comment by shighcloud-ea** [comment]
Any luck here?

**Comment by danieldekay** [comment]
'pip install knowledge_storm' completes succesfully on version 0.2.5
