### ISSUE TITLE
Why does the front-end page of the official website differ from this code?

### ISSUE THREAD

**Issue by sunshinecf** [stanford-oval/storm#124]
Can you provide the official front-end page? Thank you.

**Comment by Yucheng-Jiang** [comment]
Hi, we provide `frontend/demo_light` as a handy light weighted tool for developers to use. For official front-end page (i.e. http://storm.genie.stanford.edu), we have no plan to release it in the near future. You are welcome to contribute to demo_light or using the official web application. Hope it helps.
