### ISSUE TITLE
SerperRM does not add Title and URL in collected_results

### ISSUE THREAD

**Issue by akilgiri** [stanford-oval/storm#131]
When running STORM with SerperRM, I noticed that the URLs and Titles in raw_search_results.json were not being populated.

I think the issue is caused by lines 435 and 436 in the SerperRM class in storm/knowledge_storm
/rm.py
When I change **result.get** to **organic.get**, the URLs and Titles are populated.
![image](https://github.com/user-attachments/assets/fe0bf309-1e6c-4b79-9c3c-084982a74893)

**Comment by Yucheng-Jiang** [comment]
Thanks for reporting this. Your PR is merged. Feel free to close this issue if it resolves the error.
