### ISSUE TITLE
[BUG] Raise Error in utils.py

### ISSUE THREAD

**Issue by chironliu** [stanford-oval/storm#140]
**Describe the bug**
[storm](https://github.com/stanford-oval/storm/tree/main)/[knowledge_storm](https://github.com/stanford-oval/storm/tree/main/knowledge_storm)/utils.py

line 605:
            `    output_format="txt",`
is it should 
```
             article_text = extract(
                h,
                include_tables=False,
                include_comments=False,
                # output_format="text",
                output_format="txt",
            )
```
？

**Comment by shaoyijia** [comment]
Based on my test, "text" and "txt" does not make a difference. I still fix this nit to better match the documentation.
