### ISSUE TITLE
[BUG]  The "basic fact writer ","economic analyst","investment advisor" didn't seem to be working

### ISSUE THREAD

**Issue by xiaohuozilalala** [stanford-oval/storm#141]
**Describe the bug**
Thank you for your contribution to the project. When I tried it out through "https://storm.genie.stanford.edu/", I found that most of the questions raised by "basic fact writer", "economic analyst", "investment advisor" and "commodity trader" in the "See BrainSTORMing Process" process did not seem to be answered (see the attached picture below). Will this have a significant impact on the effect of the generated article? Is there a way to adjust it?

**To Reproduce**

 The topics I used are “Gold price forecast and influencing factors in the next 6 months” and “Gold price trends and influencing factors”.

**Screenshots**

![basic fact writer](https://github.com/user-attachments/assets/75ef5a20-c6d2-45ff-9ead-c7c65552541e)

![commodity trader](https://github.com/user-attachments/assets/5f2c62e7-7f51-4f8a-aa74-8e2a4269cb99)

![economic analyst](https://github.com/user-attachments/assets/0160e961-fc76-43b2-acad-6801b6e2fbd2)

![investment advisor](https://github.com/user-attachments/assets/11bd2eda-e6d1-4f4d-b264-67fc236dd102)

**Comment by shaoyijia** [comment]
Thanks for reporting! We were doing some internal testing yesterday on our hosted demo. The problem is due to trying to switch another language model. We have rolled back the hosted demo.

**Comment by xiaohuozilalala** [comment]
Thanks for your reply. I retested with a new topic, "A general competency model for middle-level managers," but the problem seems to still exist. (The attached picture shows the situation of one of the experts. The responses of all four experts are "Sorry, I don't have enough information to answer the question.") If I run the project locally and use a specific LLM (such as gpt4o), will this problem be improved? Or is it that the experts have actually played a role, but it is just displayed as such?
![image](https://github.com/user-attachments/assets/d52ad404-f078-403a-90f7-6eaf2edd12d1)

**Comment by Yucheng-Jiang** [comment]
@xiaohuozilalala We haven't deployed the rollback version yet. We'll update the LM on web application within 48 hrs.

**Comment by Yucheng-Jiang** [comment]
update: we have rolled back LM model. This issue should be mitigated.
