### ISSUE TITLE
Allium roseum

### ISSUE THREAD

**Issue by Aziz-Sw** [stanford-oval/storm#142]
**Describe the bug**

**To Reproduce**
Report following things
1. Input topic name
2. All output files generated for this topic as a zip file.

**Screenshots**

**Environment:**
 - OS: [e.g. iOS, Windows]
 - Browser [e.g. chrome, safari] if the bug report is UI problem

**Comment by Yucheng-Jiang** [comment]
close the issue as no information filled for bug report template.
