### ISSUE TITLE
Question Regarding 'Elaborated Box' in Web Service 

### ISSUE THREAD

**Issue by Dean-98543** [stanford-oval/storm#150]
Hello, Thank you for your valuable work.

I noticed a feature that I can type in extra information to elaborate the purpose of the topic, but I couldn't find the source code for this feature in the repository. And does the text in this box have an impact on article writing?😇

![image](https://github.com/user-attachments/assets/72659eff-d360-41bb-9a26-c61c22c52b4a)

**Comment by Yucheng-Jiang** [comment]
Hi, thanks for your interest in our work. 

No, the writing purpose does not affect the writing output. It just serves as user input sanity check and future research purposes.

**Comment by Dean-98543** [comment]
Ok, Thanks for your quick reply.
