### ISSUE TITLE
Running multiple retrieval models (rm)

### ISSUE THREAD

**Issue by Saulti23** [stanford-oval/storm#153]
Hi I want to ask I was able to run yourm and vectorrm however it only works separately. Is there something I'm missing out on or a way to use two retrievers or more on the same run ??

**Comment by shaoyijia** [comment]
@AMMAS1, any idea on this?

**Comment by AMMAS1** [comment]
Yes, this is already in development and would be added soon enough!

**Comment by Saulti23** [comment]
I actually sat on my laptop the past 12 hours and was able to get it fully working and functional I'll do some more testing this week and raise a PR

**Comment by Yucheng-Jiang** [comment]
@Saulti23 feel free to create a PR and we're happy to review and integrate the effort. Close this issue now.
