### ISSUE TITLE
Questions about DSPy Optimizers

### ISSUE THREAD

**Issue by etwk** [stanford-oval/storm#164]
DSPy is a important part of this project, I haven't seen code that load optimizer output into module.

Do you use DSPy optimizers for prompting? Could you share some of your experience with that? It will be very helpful for people to understand better about this project.

Thanks.

**Comment by shaoyijia** [comment]
Thanks for your question! The project is developed before many cool DSPy optimizers came out, so we haven't included them in our codebase.

Using DSPy optimizers to optimize prompts could be a cool thing to explore especially when you want to run STORM with smaller LMs. I would suggest initiating a discussion in DSPy community where you are more likely to get response or useful experience.
