### ISSUE TITLE
Using Open Source LLMs

### ISSUE THREAD

**Issue by dhakalnirajan** [stanford-oval/storm#173]
Please add Open Source LLMs and not proprietary models for API cost cutting.

**Comment by shaoyijia** [comment]
You can connect STORM with open LMs through common inference server like VLLM, TGI. We have provided corresponding support in [lm.py](https://github.com/stanford-oval/storm/blob/main/knowledge_storm/lm.py) `VLLMClient`, `TGIClient`.

We also provide an [example script](https://github.com/stanford-oval/storm/blob/main/examples/run_storm_wiki_mistral.py) to show how you can run STORM with `VLLMClient`.

**Comment by shaoyijia** [comment]
Close this issue for now since it is already supported.
