### ISSUE TITLE
Pylint alerts corrections as part of intervention experiment

### ISSUE THREAD

**Issue by evidencebp** [stanford-oval/storm#174]
I'd like to conduct a software engineering experiment regarding the benefit of Pylint alerts removal.
The experiment is described [here](https://github.com/evidencebp/pylint-intervention/).
In the experiments, Pylint is used with some specific alerts, files are selected for intervention and control. 
After the interventions are done, one can wait and examine the results.

I'm asking your approval for conducting the interventions in your repositories.The interventions are expected to benefit the project and will submitted in PR for approval.

These are the [planed interventions](https://github.com/evidencebp/pylint-intervention/blob/main/interventions/stanford-oval_storm_interventions_September_22_2024.csv).

**Comment by shaoyijia** [comment]
Sorry, we adopt [black](https://github.com/psf/black) for arranging and formatting Python code under `knowledge_storm`. We cannot adopt your interventions as it will break the current contribution pipeline. I am sorry for this.

**Comment by shaoyijia** [comment]
Could you restrict the modification to exclude files under `knowledge_storm`? I do hope to support your research, but files under `knowledge_storm` is linked to our python package and production demo. I don't have bandwidth to review all those critical changes.

**Comment by evidencebp** [comment]
> Could you restrict the modification to exclude files under `knowledge_storm`? I do hope to support your research, but files under `knowledge_storm` is linked to our python package and production demo. I don't have bandwidth to review all those critical changes.

Sure, I will. 
Thanks!

**Comment by shaoyijia** [comment]
Sounds great. You could add more description to the PR once you have it and marked me as reviewer.

**Comment by evidencebp** [comment]
Sure.
I removed the knowledge_strome files from the [planed interventions](https://github.com/evidencebp/pylint-intervention/blob/main/interventions/stanford-oval_storm_interventions_September_22_2024.csv).

**Comment by evidencebp** [comment]
@shaoyijia , please note the [PR](https://github.com/stanford-oval/storm/pull/181)

Thanks!

**Comment by shaoyijia** [comment]
Yucheng helps review this PR. Could you check out his comment?

**Comment by evidencebp** [comment]
Sure, I answered in the PR.

Thank you both for your help!
