### ISSUE TITLE
Responsive website for mobile users 

### ISSUE THREAD

**Issue by buildcore** [stanford-oval/storm#18]
The demo (storm.genie.stanford.edu) doesn't look responsive on some devices.
As illustrated in the figure below: the "Important Note" popup is not responsive and hides the button to continue to the app. 

![Screenshot 2024-04-16 at 00 54 50](https://github.com/stanford-oval/storm/assets/95249675/9677d84d-bba4-4e50-adf4-e8192755f0b4)

**Comment by shaoyijia** [comment]
Could you share your mobile device info?

**Comment by GOUTHAM-2002** [comment]
Can i work on this and make it responsive for mobile devices too ?

**Comment by buildcore** [comment]
@shaoyijia Tested on Redmi 12C, iPhone SE and iPhone 12

I cannot reproduce the error as the Streamlit demo part is not included in the source code, right.

**Comment by shaoyijia** [comment]
Thanks for testing!

Yes, the web application code is not released as this part is for in-the-wild experiment purpose and is integrated with our own backend.

**Comment by DeathGanker** [comment]
web应用有发布计划吗？目前仅仅是后台输出所有的文章和引用内容，前端页面不知该怎么去适配

**Comment by Yucheng-Jiang** [comment]
@buildcore We released a new UI available at http://storm.genie.stanford.edu recently. It should be better on mobile now.
@DeathGanker We also released demo light, a handy tool for developers. check it out in our release notes: https://github.com/stanford-oval/storm/releases/tag/v0.2.0.
