### ISSUE TITLE
Co-STORM how to get url_to_info.json

### ISSUE THREAD

**Issue by xiaobeicn** [stanford-oval/storm#188]
only 
log.json           # Log of information-seeking conversation
report.txt         # Final article generated

**Comment by Yucheng-Jiang** [comment]
Hi, you can do following to save the system state.
```python
with open(os.path.join(output_dir, "costorm_instance_dump.json"), "w") as f:
    instance_copy = costorm_runner.to_dict()
    json.dump(instance_copy, f, indent=2)
```

in this dict, you may find the collected information under `instance_copy["knowledge_base"]["info_uuid_to_info_dict"]`.

KnowledgeBase is a new information organization interface we introduce in CoSTORM with definition [here](https://github.com/stanford-oval/storm/blob/0a902cd51206e084d1ad27d4e2e774567a3d7145/knowledge_storm/dataclass.py#L291). `info_uuid_to_info_dict` is a dictionary with key as reference index shown in the discourse and generated report, and value is the Information collected, which type is defined [here](https://github.com/stanford-oval/storm/blob/0a902cd51206e084d1ad27d4e2e774567a3d7145/knowledge_storm/interface.py#L41)
