### ISSUE TITLE
FEATURE REQUEST: Local LLM endpoint integration (like Ollama and OpenAI API compatible) and Docker Container

### ISSUE THREAD

**Issue by mjtechguy** [stanford-oval/storm#2]
This project seems awesome. Thanks for building this.

Would it be possible to:

1. Expose a variable for the LLM Endpoint address so systems like Ollama could be used as OpenAI API compatible endpoints?
2. Would you be able to offer the tool / UI as a Docker container or Docker Compose stack?

Thanks!

**Comment by shaoyijia** [comment]
For 1, you can change the LLM configuration according to https://github.com/stanford-oval/storm?tab=readme-ov-file#customize-the-storm-configurations.

For 2, having a Docker release sounds like a good idea. We will consider this.

**Comment by shaoyijia** [comment]
Hi @shuther , thanks for the info! Are you willing to help with ollama integration to see whether it's feasible? We develop STORM using dspy and I just found they support ollama in [their codebase](https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/ollama.py). New LM integration can be added in [`src/lm.py`](https://github.com/stanford-oval/storm/blob/main/src/lm.py).

**Comment by shaoyijia** [comment]
Hi @shuther , thank you so much!

I feel we can leverage the effort in https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/ollama.py, though some testing is needed and we may need to create a wrapper instead of directly using it (you can check out examples in [`src/lm.py`](https://github.com/stanford-oval/storm/blob/main/src/lm.py)).

When testing Mistral 7B, I found although it's worth than GPT (which is as expected), it can do a pretty good job in the knowledge curation part (i.e., finding and organizing information). That's why I think ollama integration is interesting.

**Comment by shaoyijia** [comment]
> It could make sense to focus on this one or you have a concern?

No concern, this is good. I think https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/ollama.py is also implemented based on it. You may check whether their implementation can directly work or not. If not, we also hope to inherit `dspy.LM`. In this way, we can pass the model object into [`STORMWikiLMConfigs`](https://github.com/stanford-oval/storm/blob/5d21c393e64d8c877ae6a9db3a0df0a72a926b33/src/storm_wiki/engine.py#L21) without changing anything else. For example, people may use Ollama to run STORM in this way:

```python
lm_configs = STORMWikiLMConfigs()

conv_simulator_lm = OllamaModel(...)
question_asker_lm = OllamaModel(...)
outline_gen_lm = OllamaModel(...)
article_gen_lm = OllamaModel(...)
article_polish_lm = OllamaModel(...)

# LM setup.
lm_configs.set_conv_simulator_lm(conv_simulator_lm)
lm_configs.set_question_asker_lm(question_asker_lm)
lm_configs.set_outline_gen_lm(outline_gen_lm)
lm_configs.set_article_gen_lm(article_gen_lm)
lm_configs.set_article_polish_lm(article_polish_lm)

# STORM pipeline setup (independent with LM setup).
engine_args = STORMWikiRunnerArguments(...)

# User / Other functions only need to call runner, and do not need to think about Ollama after they are set up.
runner = STORMWikiRunner(engine_args, lm_configs)
```

> llama3 may worth a try.

Totally. I only provide an example with Mistral because I haven't got time to configure llama3 yet - but it's really worth a try.

**Comment by Yucheng-Jiang** [comment]
@shuther  The error `root : ERROR    : Error occurs when searching query : 'hits'` you see is most likely due to rate limit exceeds from You.com search engine API. (check if you have some error log looks like this #28)

**Comment by Yucheng-Jiang** [comment]
@shuther Also, note that the argument `--remove-duplicate` should go with `--do-polish-article` as the argument controls over whether remove duplicate content after final article generation. It does nothing when you don't specify `--do-polish-article`.

**Comment by Yucheng-Jiang** [comment]
@shuther Would you mind provide full log of running the command? Also please confirm that you are on the head of main branch.

**Comment by Yucheng-Jiang** [comment]
seems like `storm/./src/lm.py`, line 191, should be `self.history.append(json_serializable_history)` instead of `(RateLimitError,),`. Could you confirm you are at head of main branch?

**Comment by shaoyijia** [comment]
> is it possible to change the model from paraphrase-MiniLM-L6-v2 to ollama/all-minilm (using openai/litellm compatible endpoint)

This is possible, though you need to check its performance. This model is used to retrieve collected information to write each section. Here is an example for how to use `ollama/all-minilm`

1. Create `OllamaStormInformationTable` inheriting `StormInformationTable` but using ollama for retrieving information from the information table.
```
import numpy as np
import ollama  # Assume ollama is already installed on the PC and you have already run `ollama pull all-minilm`

class OllamaStormInformationTable(InformationTable):
    """Manage StormInformation with ollama embedding model."""

    def prepare_table_for_retrieval(self):
        self.encoder = SentenceTransformer('paraphrase-MiniLM-L6-v2')
        self.collected_urls = []
        self.collected_snippets = []
        for url, information in self.url_to_info.items():
            for snippet in information.snippets:
                self.collected_urls.append(url)
                self.collected_snippets.append(snippet)
                # This part is new.
                self.encoded_snippets.append(ollama.embeddings(model='all-minilm', prompt=snippet)['embeddings'])
        self.encoded_snippets = np.array(self.encoded_snippets)

    def retrieve_information(self, queries: Union[List[str], str], search_top_k) -> List[StormInformation]:
        selected_urls = []
        selected_snippets = []
        if type(queries) is str:
            queries = [queries]
        for query in queries:
            # This line is new.
            encoded_query = np.array(ollama.embeddings(model='all-minilm', prompt=query)['embeddings'])
            sim = cosine_similarity([encoded_query], self.encoded_snippets)[0]
            sorted_indices = np.argsort(sim)
            for i in sorted_indices[-search_top_k:][::-1]:
                selected_urls.append(self.collected_urls[i])
                selected_snippets.append(self.collected_snippets[i])

        url_to_snippets = {}
        for url, snippet in zip(selected_urls, selected_snippets):
            if url not in url_to_snippets:
                url_to_snippets[url] = set()
            url_to_snippets[url].add(snippet)

        selected_url_to_info = {}
        for url in url_to_snippets:
            selected_url_to_info[url] = copy.deepcopy(self.url_to_info[url])
            selected_url_to_info[url].snippets = list(url_to_snippets[url])

        return list(selected_url_to_info.values())
```
2. Customize `STORMWikiRunner` to use `OllamaStormInformationTable`.
```
class MySTORMWikiRunner(STORMWikiRunner):

    """Customize STORMWikiRunner to use OllamaStormInformationTable."""
    def run(self,
        topic: str,
        ground_truth_url: str = '',
        do_research: bool = True,
        do_generate_outline: bool = True,
        do_generate_article: bool = True,
        do_polish_article: bool = True,
        remove_duplicate: bool = False,
        callback_handler: BaseCallbackHandler = BaseCallbackHandler()):
    self.topic = topic
    self.article_dir_name = topic.replace(' ', '_').replace('/', '_')
    self.article_output_dir = os.path.join(self.args.output_dir, self.article_dir_name)
    os.makedirs(self.article_output_dir, exist_ok=True)

    # research module
    information_table: OllamaStormInformationTable = None  # StormInformationTable -> OllamaStormInformationTable
    if do_research:
        information_table = self.run_knowledge_curation_module(ground_truth_url=ground_truth_url,
                                                               callback_handler=callback_handler)
    else:
        information_table = OllamaStormInformationTable.from_conversation_log_file(
            os.path.join(self.article_output_dir, 'conversation_log.json'))  # StormInformationTable -> OllamaStormInformationTable

    # outline generation module
    outline: StormArticle = None
    if do_generate_outline:
        outline = self.run_outline_generation_module(information_table=information_table,
                                                     callback_handler=callback_handler)
    else:
        outline = StormArticle.from_outline_file(topic=topic, file_path=os.path.join(self.article_output_dir,
                                                                                 'storm_gen_outline.txt'))

    # article generation module
    draft_article: StormArticle = None
    if do_generate_article:
        draft_article = self.run_article_generation_module(outline=outline,
                                                           information_table=information_table,
                                                           callback_handler=callback_handler)

    # article polishing module
    if do_polish_article:
        polished_article = self.run_article_polishing_module(draft_article=draft_article,
                                                             remove_duplicate=remove_duplicate)
```

If you want to use https://docs.litellm.ai/docs/providers/ollama instead of https://github.com/ollama/ollama-python, you just need to change the `ollama.embeddings(...)` to corresponding call to litellm API.

**Comment by shaoyijia** [comment]
> root : ERROR    : Error occurs when searching query : 'hits'
> root : ERROR    : Error occurs when searching query : 'hits'
> root : ERROR    : Error occurs when searching query : 'hits'
> interface : INFO     : run_knowledge_curation_module executed in 1.4256 seconds
> interface : INFO     : run_outline_generation_module executed in 3.9669 seconds

Based on the log, it seems like the `do_research` part is not correctly executed, i.e., no information is collected. Could you check whether YouRM is working? It may be exceeding the search API limit, so no information is returned when calling the retriever. To check this, you can do the following
```
from rm import YouRM

you_rm = YouRM(ydc_api_key="you_com_api_key")
output = you_rm(query_or_queries="Differences between capitalism and liberalism", exclude_urls=[])
print(output)
```

**Comment by Yucheng-Jiang** [comment]
Ollama is supported now by #81. For other bug report, please open a new issue with bug report template.

**Comment by sammcj** [comment]
Fantastic work! Thanks @Yucheng-Jiang
