### ISSUE TITLE
I also got this error with live demo.

### ISSUE THREAD

**Issue by Octobot222** [stanford-oval/storm#21]
I also got this error with live demo.

_Originally posted by @Coding4fun2012 in https://github.com/stanford-oval/storm/issues/12#issuecomment-2053667072_

**Comment by Yucheng-Jiang** [comment]
As mentioned in linked issue, it occurs as the search API has exceeded its maximum limit due to an unprecedented level of demand. We're actively reaching out to our third-party provider to resolve this issue. Please stay tuned for updates!
