### ISSUE TITLE
[Question] Implementing a custom vector store for the retrieval module

### ISSUE THREAD

**Issue by williambrach** [stanford-oval/storm#210]
I'm looking to replace the current Internet search (e.g., BingSearch) with my own vector store (Qdrant) in the retrieval module. Based on the README, I understand this should be possible by adding an implementation for my vector store in `knowledge_storm/rm.py`.

Questions:

1. Are there any existing implementations of vector stores for the retrieval module?
2. Can you confirm that adding a custom implementation in `knowledge_storm/rm.py` is the correct approach? Custom implementation should return documents in the same format as other retrievers.

Any guidance or examples would be greatly appreciated. Thank you!

**Comment by shaoyijia** [comment]
> Are there any existing implementations of vector stores for the retrieval module?

Please check out [`VectorRM`](https://github.com/stanford-oval/storm/blob/main/knowledge_storm/rm.py#L183) to see whether it fits you need. See example usage [here](https://github.com/stanford-oval/storm/tree/main/examples/storm_examples#run-storm-with-your-own-corpus)

> Can you confirm that adding a custom implementation in knowledge_storm/rm.py is the correct approach? Custom implementation should return documents in the same format as other retrievers.

Yes.

**Comment by williambrach** [comment]
> > Are there any existing implementations of vector stores for the retrieval module?
> 
> Please check out [`VectorRM`](https://github.com/stanford-oval/storm/blob/main/knowledge_storm/rm.py#L183) to see whether it fits you need. See example usage [here](https://github.com/stanford-oval/storm/tree/main/examples/storm_examples#run-storm-with-your-own-corpus)
> 
> > Can you confirm that adding a custom implementation in knowledge_storm/rm.py is the correct approach? Custom implementation should return documents in the same format as other retrievers.
> 
> Yes.

Thank you for your prompt response!

This is exactly what I was looking for :)
