### ISSUE TITLE
Prompts folder is missing

### ISSUE THREAD

**Issue by czy1999** [stanford-oval/storm#24]
Great work! 

The provided evaluation code includes a argument that references a prompt file path:
```python
parser.add_argument("--prompt_template_path", default="./prompts/eval_prometheus_no_ref.prompt",
```
However, the expected directory structure in the repository does not include a prompts folder. This discrepancy prevents the code from running successfully as it cannot find the specified file.

**Comment by Yucheng-Jiang** [comment]
For the quick reference, you can find the prompt in table 8 in our paper: https://arxiv.org/pdf/2402.14207.pdf

**Comment by shaoyijia** [comment]
Hi @czy1999 , thanks for your interest! We just updated `eval` to include the prompt file.

**Comment by czy1999** [comment]
Thanks!
