### ISSUE TITLE
[BUG] mobile UI compatibility

### ISSUE THREAD

**Issue by zvdy** [stanford-oval/storm#241]
**Frontend Mobile UI issues**
There are a few UI issues when interacting with the web using mobile devices, padding is off and overlapping happens.

**To Reproduce**
1. Use an iPhone Device or mimic the UI using DevTools.
2. Use the web normally and you will face the issues, any input triggers the issue.

**Screenshots**
![image](https://github.com/user-attachments/assets/981027f4-329e-489b-b4db-89849211cb4a)
![image](https://github.com/user-attachments/assets/ce978c4f-076f-4e9b-8799-8eeed8fd25f5)
![image](https://github.com/user-attachments/assets/ad86e8e6-3e8c-4da2-9900-8ca5752ab6be)

**Environment:**
 - OS: IOS
 - Browser: Any

_edit: added more screenshots and tested in other browsers, still fails, there are quite a few UI issues_

**Comment by shaoyijia** [comment]
Thanks for reporting. Currently, we don't have immediate plan to support mobile UI.

**Comment by dekunma** [comment]
@zvdy we had some bandwidth last week and fixed these issues. Thank you for reporting them!

**Comment by zvdy** [comment]
@dekunma great to hear! 🚀
