### ISSUE TITLE
[BUG] User Data Protection Issues - Data Sharing Terms Need Strengthening

### ISSUE THREAD

**Issue by souzatharsis** [stanford-oval/storm#246]
**Describe the bug**

1. Privacy policy is missing. 
2. T&C language (below) is vague. As it defines data shares can be licensed under CC-BY or "similar license"
3. Additionally, users should have the right not to share their data for potential commercial use.

There should be better protections for user data, particularly for a Stanford open source project.

**To Reproduce**
Login for the first time. T&C content is available in popup: Important Note.

**Screenshots**
![image](https://github.com/user-attachments/assets/7dda9e09-eec5-481c-8cf6-9a71c717d11e)

**Environment:**
 - OS: Ubuntu
 - Browser Chrome

**Comment by Yucheng-Jiang** [comment]
Thank you for your interest in the STORM project.

STORM operates as part of an ongoing IRB-approved user study. We collect data for research purposes, adhering to strict standards to ensure that data remains anonymized, **without linkage to personally identifiable information (PII)**. By using the STORM website, users consent to data collection and usage solely for advancing research, **with no commercial intent**.

To support transparency and enable others to build upon or host our work, we’ve open-sourced a minimal UI and codebase in this repository, allowing public access to essential STORM and Co-STORM functionalities.

Regarding GitHub issues, please note that **this platform is primarily for bug reports and feature requests**. For further inquiries on this topic, feel free to reach out to us at [genie@cs.stanford.edu](mailto:genie@cs.stanford.edu).

Thank you for your understanding, and please let us know if you have further concerns.
