### ISSUE TITLE
[BUG] ImportError: cannot import name 'AzureAISearch' from 'knowledge_storm.rm' 

### ISSUE THREAD

**Issue by Elusv** [stanford-oval/storm#265]
**Describe the bug**
ImportError: cannot import name 'AzureAISearch' from 'knowledge_storm.rm' 

**To Reproduce**
pip install knowledge-storm
pip install knolwledge-storm-upgrade
python examples/storm_examples/run_storm_wiki_gpt.py --output-dir . --retriever you --do-research --do-generate-outline --do-generate-article --do-polish-article

**Environment:**
 - OS: MacOS (Intel)

**Comment by shaoyijia** [comment]
Updated our pypi version. Run `pip install knowledge-storm --upgrade` again and it should be fixed now. Thanks for reporting this!
