### ISSUE TITLE
root: Error : Error occours

### ISSUE THREAD

**Issue by HolgerGelhausen** [stanford-oval/storm#28]
I would normally say that I didn't do anything. It stopped working from one day to the next, and I reinstalled again. The search engine says searches are coming in, what can I do? Thank you
![youcom@2x_fs8](https://github.com/stanford-oval/storm/assets/100290914/a1b30de1-c1d0-44a9-a7b5-6845ec3ffb23)

Thanks for help

 % python -m scripts.run_prewriting --input-source console --engine gpt-4 --max-conv-turn 5 --max-perspective 5 --do-research
Topic: Solving the 6 W Questions with WardleyMaps
Ground truth url (will be excluded from source): 
root : ERROR    : Error occurs when searching query What are WardleyMaps?: 'hits'
root : ERROR    : Error occurs when searching query Wardley Maps "Who" aspect: 'hits'
root : ERROR    : Error occurs when searching query What are the 6 W Questions?: 'hits'
root : ERROR    : Error occurs when searching query Can you provide an example of using Wardley Maps to answer the 6 W questions in technology roadmapping?: 'hits'
root : ERROR    : Error occurs when searching query Understanding "Who" in Wardley Mapping: 'hits'
root : ERROR    : Error occurs when searching query How can WardleyMaps be used to solve the 6 W Questions?: 'hits'
root : ERROR    : Error occurs when searching query What are Wardley Maps?: 'hits'
root : ERROR    : Error occurs when searching query Identifying stakeholders with Wardley Maps: 'hits'
root : ERROR    : Error occurs when searching query What is Wardley Mapping?: 'hits'

**Comment by shaoyijia** [comment]
The error seems to be hitting the free tier limit.

**Comment by HolgerGelhausen** [comment]
Thank you very much for your help i will check it. I did not get any warning from you.com

**Comment by shaoyijia** [comment]
Yeah, you could test the API separately by only running the `YouRM` in `src/rm.py`. I suspect this when we are debugging this issue #12, we got similar errors.

**Comment by eyangs** [comment]
The same error, even though I have paid for the Bing API!

**Comment by FriedVariable** [comment]
Same here with you.com free API. Any plan to intergrate searxng?

**Comment by Yucheng-Jiang** [comment]
@FriedVariable searxng is already supported by #119.

**Comment by Yucheng-Jiang** [comment]
Close this issue for now. If run into any problem, feel free to open another issue with bug report template.
