### ISSUE TITLE
no evaluation prompt for replicate the result?

### ISSUE THREAD

**Issue by Xccanxin** [stanford-oval/storm#29]
no ./prompts/eval_prometheus_no_ref.prompt file for eval/evaluation_prometheus.py?
Could you please show what this file looks like? Does it directly use the code from https://github.com/kaistAI/prometheus/tree/main?

e.g.
###Task Description:
An instruction (might include an Input inside it), a response to evaluate, a reference answer that gets a score of 5, and a score rubric representing a evaluation criteria are given.
1. Write a detailed feedback that assess the quality of the response strictly based on the given score rubric, not evaluating in general.
2. After writing a feedback, write a score that is an integer between 1 and 5. You should refer to the score rubric.
3. The output format should look as follows: \"Feedback: (write a feedback for criteria) [RESULT] (an integer number between 1 and 5)\"
4. Please do not generate any other opening, closing, and explanations.

###The instruction to evaluate:
{orig_instruction}

###Response to evaluate:
{orig_response}

###Reference Answer (Score 5):
{orig_reference_answer}

###Score Rubrics:
[{orig_criteria}]
Score 1: {orig_score1_description}
Score 2: {orig_score2_description}
Score 3: {orig_score3_description}
Score 4: {orig_score4_description}
Score 5: {orig_score5_description}

###Feedback:

**Comment by shaoyijia** [comment]
Hi, the prompt file is in [`eval/eval_prometheus_no_ref.prompt`](https://github.com/stanford-oval/storm/blob/main/eval/eval_prometheus_no_ref.prompt) and the rubric file is in [`eval/eval_rubric_5.json`](https://github.com/stanford-oval/storm/blob/main/eval/eval_rubric_5.json).

**Comment by Xccanxin** [comment]
> Hi, the prompt file is in [`eval/eval_prometheus_no_ref.prompt`](https://github.com/stanford-oval/storm/blob/main/eval/eval_prometheus_no_ref.prompt) and the rubric file is in [`eval/eval_rubric_5.json`](https://github.com/stanford-oval/storm/blob/main/eval/eval_rubric_5.json).

thanks for updates
