### ISSUE TITLE
I think this writing process is very good and can help you improve a commercial version. For example:  https://www.versabot.cn

### ISSUE THREAD

**Issue by uniconnector** [stanford-oval/storm#3]
Hello, I think this writing process is very good and can help you improve a commercial version.
For example: 
          https://www.versabot.cn

https://github.com/stanford-oval/storm/assets/67131938/46eaf051-b166-4ceb-9f02-eb15bcff2683

**Comment by Yucheng-Jiang** [comment]
Thanks for sharing! We release a new UI recently, check it out at http://storm.genie.stanford.edu.
