### ISSUE TITLE
如何更改open_ai_base地址

### ISSUE THREAD

**Issue by DeathGanker** [stanford-oval/storm#37]
我是通过代理的方式访问openai网站，查看了源码没有找到更新open_ai_base的地址，请帮忙解答，感激不尽

**Comment by kimoji919** [comment]
设置模型那块，apibase可以直接改

**Comment by DeathGanker** [comment]
你是说secrets.toml里么，只有azure的api_base，open_ai的没有设置项

**Comment by shaoyijia** [comment]
Hello, if you directly use the API provided by OpenAI, you do need to set api_base (i.e., you just need to leave that field empty). Check out OpenAI python API documentation for more information: https://github.com/openai/openai-python

**Comment by enimo** [comment]
在 src/storm_wiki/engine.py文件中初始化部分，把 `api_base: None`，改成 `api_base: api_base`即可。

<img width="903" alt="image" src="https://github.com/user-attachments/assets/6a74a356-7bd9-4b65-89f6-2b5408aab703">

**Comment by PPG0D** [comment]
我也遇到了这个问题，请问最后是如何解决的

**Comment by enimo** [comment]
> 我也遇到了这个问题，请问最后是如何解决的

如上，需改动一下api_base部分的源码，然后使用secrets.toml里azure的api_base即可

**Comment by sunshinecf** [comment]
大佬厉害了，还能看懂中文

**Comment by Yucheng-Jiang** [comment]
will close this issue if don't have further discussion by end of this week.
