### ISSUE TITLE
Web Service Interface Requested

### ISSUE THREAD

**Issue by dotnetpie** [stanford-oval/storm#41]
STORM is a valuable tool. However, deploying it for a number of users is hard. Providing the basic web interface for using this tool is, like the Demo site, very handy and wanted. Thanks for your consideration.

**Comment by Yucheng-Jiang** [comment]
Hi @dotnetpie , hanks for the feature request and appreciate the feedback as it helps us understand the needs of our users and prioritize future enhancements.

Regarding the web interface for STORM, we hear you on that pain point. We have plans to release a stand-alone minimal UI specifically designed for **development purposes** in our upcoming release.

Improving UI for better user experience is on our road map, so stay tuned for updates on that front!

**Comment by dotnetpie** [comment]
Hello STORM team, Nice to hear that. Thanks for your consideration and looking forward to your updates.

**Comment by Yucheng-Jiang** [comment]
@dotnetpie  We released a new UI available at http://storm.genie.stanford.edu/ recently. We also released demo light, a handy tool for developers. check it out in our release notes: https://github.com/stanford-oval/storm/releases/tag/v0.2.0.
