### ISSUE TITLE
Integration of Groq “mixtral-8x7b-32768" LLM in STORM

### ISSUE THREAD

**Issue by jbdatascience** [stanford-oval/storm#48]
I would like the integration of Groq “mixtral-8x7b-32768" LLM in STORM.

For further information on Groq LLM models, see:

https://python.langchain.com/v0.1/docs/integrations/chat/groq/

and

https://console.groq.com/docs/models

**Comment by Yucheng-Jiang** [comment]
We have create [contribution documentation](https://github.com/stanford-oval/storm/blob/main/CONTRIBUTING.md) and would love to merge effort contributing to integration of various models.

**Comment by Yucheng-Jiang** [comment]
close this issue as resolved by #144
