### ISSUE TITLE
Copyright infringing relicensing of wikipedia content

### ISSUE THREAD

**Issue by stuartyeates** [stanford-oval/storm#51]
It appears that the content in https://github.com/stanford-oval/storm/tree/main/FreshWiki/txt is copies of the text of wikipedia articles.

The entire repository is licensed as MIT (per https://github.com/stanford-oval/storm/blob/main/LICENSE).

This appears to represent a copyright-infringing relicensing of this content. 

Please see https://en.wikipedia.org/wiki/Wikipedia:Reusing_Wikipedia_content

**Comment by shaoyijia** [comment]
Hi @stuartyeates , thank you so much for pointing this out! We are very grateful to Wikipedia for their excellent open-source content and are sorry about our previous oversight. We have updated the LICENSE according to the guideline you shared.

Feel free to let us know if there is further concern.
