### ISSUE TITLE
SentenceTransformer IndexError: list index out of range 

### ISSUE THREAD

**Issue by robeson1010** [stanford-oval/storm#62]
![image](https://github.com/stanford-oval/storm/assets/27775667/7203b0aa-9c75-485e-ab32-cdc25efb567c)

**Comment by tstanek390** [comment]
Having the same issue with Anthropic, any ideas on this? thx

**Comment by Excidos** [comment]
Having the same issue

**Comment by sewellxie** [comment]
having the same issue, has anyone else meet and resolved this problem?

**Comment by Yucheng-Jiang** [comment]
@sewellxie This issue occurs most likely due to no information is successfully retrieved. Please check if retriever model is working as desired.

**Comment by sunshinecf** [comment]
我也是

**Comment by Yucheng-Jiang** [comment]
close this thread now. If run into similar issue, please open a new issue with bug report template.
