### ISSUE TITLE
Provide other language output

### ISSUE THREAD

**Issue by Zzaa2020** [stanford-oval/storm#63]
Should have another agent to do the translation the whole content to a specific language using LLM. And on the web interface provide a option for user to choose the output language, so the final output report should written in that language.

**Comment by Yucheng-Jiang** [comment]
Thank you for your interest in STORM.

While we recognize the importance of multi-lingual functionality, implementing and fully testing this feature to ensure accuracy and alignment with ethical standards is a complex task. Given the current bandwidth of our team, this will not be a priority in the immediate future.

You are more than welcome to customize STORM to suit your specific needs, including multi-lingual support. Additionally, feel free to modify the demo light version under frontend/demo_light as you see fit.
