### ISSUE TITLE
Openai completions error 

### ISSUE THREAD

**Issue by smehra** [stanford-oval/storm#77]
When I run 
`python examples/run_storm_wiki_gpt.py \
    --output-dir $OUTPUT_DIR \
    --retriever you \
    --do-research \
    --do-generate-outline \
    --do-generate-article \
    --do-polish-article`
I get the following error
`TypeError: Completions.create() got an unexpected keyword argument 'api_version'`

**Comment by shaoyijia** [comment]
Hi, which version of `openai` package are you using? You can run the following code to check the version.

```
import openai
print(openai.__version__)
```

**Comment by smehra** [comment]
I created a new virtual env with the provided requirements.txt. Anyway, the version is 1.35.13

**Comment by 360elements360** [comment]
Same issue here

Traceback (most recent call last):
  File "C:\Users\Power\Documents\storm\examples\run_storm_wiki_gpt.py", line 125, in <module>
    main(parser.parse_args())
  File "C:\Users\Power\Documents\storm\examples\run_storm_wiki_gpt.py", line 80, in main
    runner.run(
  File "C:\Users\Power\Documents\storm\src\storm_wiki\engine.py", line 287, in run
    information_table = self.run_knowledge_curation_module(ground_truth_url=ground_truth_url,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\Documents\storm\src\interface.py", line 376, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\Documents\storm\src\storm_wiki\engine.py", line 164, in run_knowledge_curation_module
    information_table, conversation_log = self.storm_knowledge_curation_module.research(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\Documents\storm\src\storm_wiki\modules\knowledge_curation.py", line 304, in research
    considered_personas = self._get_considered_personas(topic=topic, max_num_persona=max_perspective)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\Documents\storm\src\storm_wiki\modules\knowledge_curation.py", line 229, in _get_considered_personas
    return self.persona_generator.generate_persona(topic=topic, max_num_persona=max_num_persona)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\Documents\storm\src\storm_wiki\modules\persona_generator.py", line 135, in generate_persona
    personas = self.create_writer_with_persona(topic=topic)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\dspy\primitives\program.py", line 26, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\Documents\storm\src\storm_wiki\modules\persona_generator.py", line 70, in forward
    related_topics = self.find_related_topic(topic=topic).related_topics
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\dspy\predict\predict.py", line 61, in __call__
    return self.forward(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\dspy\predict\chain_of_thought.py", line 59, in forward
    return super().forward(signature=signature, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\dspy\predict\predict.py", line 103, in forward
    x, C = dsp.generate(template, **config)(x, stage=self.stage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\dsp\primitives\predict.py", line 77, in do_generate
    completions: list[dict[str, Any]] = generator(prompt, **kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\Documents\storm\src\lm.py", line 76, in __call__
    response = self.request(prompt, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\dsp\modules\gpt3.py", line 144, in request
    return self.basic_request(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\dsp\modules\gpt3.py", line 117, in basic_request
    response = chat_request(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\dsp\modules\gpt3.py", line 263, in chat_request
    return v1_cached_gpt3_turbo_request_v2_wrapped(**kwargs).model_dump()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\dsp\modules\cache_utils.py", line 16, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\dsp\modules\gpt3.py", line 256, in v1_cached_gpt3_turbo_request_v2_wrapped
    return v1_cached_gpt3_turbo_request_v2(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\joblib\memory.py", line 655, in __call__
    return self._cached_call(args, kwargs)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\joblib\memory.py", line 598, in _cached_call
    out, metadata = self.call(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\joblib\memory.py", line 856, in call
    output = self.func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\dsp\modules\gpt3.py", line 250, in v1_cached_gpt3_turbo_request_v2
    return openai.chat.completions.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Power\miniconda3\Lib\site-packages\openai\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: Completions.create() got an unexpected keyword argument 'api_version'


openai package = 1.35.13

**Comment by shaoyijia** [comment]
> I created a new virtual env with the provided requirements.txt. Anyway, the version is 1.35.13

@smehra , **if you still meet this problem, you could downgrade `openai` to `0.28.1` as a quick fix**. `api_base` and `api_version` are used for calling GPT models using Azure service. `openai` 1.x defines `OpenAI` and `AzureOpenAI` as two separate classes so I suspect something goes run due to this.

I recognize by running `pip install -r requirements.txt`, the installed `openai` package will have the version of 1.35.13. We will look into this very soon as the team is working on wrapping `src` as a python package to make the installation process smoother (#66).

**Comment by Laisky** [comment]
Issue came back in the latest code; installing openai==0.28.1 didn't fix it. @shaoyijia

**Comment by shaoyijia** [comment]
@Laisky Could you tell me the result for `knowledge_storm.__version__`?

Also, if you have installed our package before, I highly recommend upgrade it with `pip install knowledge-storm --upgrade` as there have been many developments in the past few months. Very likely the issue will be solved after upgrading.

**Comment by Laisky** [comment]
cc @shaoyijia 

Finally solved the issue! Here's my requirement.txt file:

```
aiohappyeyeballs==2.4.4
aiohttp==3.11.11
aiosignal==1.3.2
alembic==1.14.0
annotated-types==0.7.0
anyio==3.7.1
APScheduler==3.11.0
asyncer==0.0.8
attrs==24.3.0
babel==2.16.0
backoff==2.2.1
beautifulsoup4==4.13.0b2
black==24.10.0
cachetools==5.5.0
certifi==2024.12.14
cffi==1.17.1
charset-normalizer==3.4.1
click==8.1.8
cloudpickle==3.1.0
colorlog==6.9.0
courlan==1.3.2
cryptography==42.0.8
datasets==2.14.7
dateparser==1.2.0
dill==0.3.7
diskcache==5.6.3
distro==1.9.0
dnspython==2.7.0
dspy==2.5.43
dspy-ai==2.5.43
duckduckgo_search==7.1.1
email_validator==2.2.0
fastapi==0.111.1
fastapi-cli==0.0.7
fastapi-sso==0.10.0
filelock==3.16.1
frozenlist==1.5.0
fsspec==2023.10.0
future==0.18.3
greenlet==3.1.1
grpcio==1.69.0rc1
grpcio-tools==1.69.0rc1
gunicorn==22.0.0
h11==0.14.0
h2==4.1.0
hpack==4.0.0
htmldate==1.9.3
httpcore==1.0.7
httptools==0.6.4
httpx==0.27.2
huggingface-hub==0.27.0
humanize==4.11.0
hyperframe==6.0.1
idna==3.10
importlib_metadata==8.5.0
Jinja2==3.1.5
jiter==0.8.2
joblib==1.3.2
json_repair==0.35.0
jsonpatch==1.33
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
jusText==3.0.1
kipp==0.2.11
langchain-core==0.3.28
langchain-huggingface==0.1.2
langchain-qdrant==0.2.0
langchain-text-splitters==0.3.4
langsmith==0.2.7
litellm==1.53.7
lxml==5.3.0
lxml_html_clean==0.4.1
magicattr==0.1.6
Mako==1.3.8
markdown-it-py==3.0.0
MarkupSafe==3.0.2
maya==0.6.1
mdurl==0.1.2
mpmath==1.3.0
multidict==6.1.0
multiprocess==0.70.15
mypy-extensions==1.0.0
networkx==3.4.2
numpy==1.26.4
nvidia-cublas-cu12==12.4.5.8
nvidia-cuda-cupti-cu12==12.4.127
nvidia-cuda-nvrtc-cu12==12.4.127
nvidia-cuda-runtime-cu12==12.4.127
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.4.127
oauthlib==3.2.2
openai==1.58.1
optuna==4.1.0
orjson==3.10.13
packaging==24.2
pandas==2.2.3
pathspec==0.12.1
pendulum==3.0.0
pillow==11.0.0
platformdirs==4.3.6
portalocker==2.10.1
primp==0.9.2
propcache==0.2.1
protobuf==5.29.2
pyarrow==18.1.0
pyarrow-hotfix==0.6
pycparser==2.22
pydantic==2.10.4
pydantic_core==2.27.2
Pygments==2.18.0
PyJWT==2.10.1
PyNaCl==1.5.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.9
pytz==2024.2
PyYAML==6.0.2
qdrant-client==1.12.2
redis==5.2.1
referencing==0.35.1
regex==2024.11.6
requests==2.32.3
requests-toolbelt==1.0.0
rfc3986==1.5.0
rich==13.9.4
rich-toolkit==0.12.0
rpds-py==0.22.3
rq==2.1.0
ruamel.yaml==0.18.8
ruamel.yaml.clib==0.2.12
safetensors==0.4.6.dev0
scikit-learn==1.6.0
scipy==1.15.0rc2
sentence-transformers==3.3.1
shellingham==1.5.4
six==1.17.0
snaptime==0.2.4
sniffio==1.3.1
soupsieve==2.6
SQLAlchemy==2.0.36
starlette==0.37.2
structlog==24.4.0
sympy==1.13.1
tenacity==9.0.0
threadpoolctl==3.5.0
tiktoken==0.8.0
time-machine==2.16.0
tld==0.13
tokenizers==0.21.0
toml==0.10.2
torch==2.5.1
tornado==6.4.2
tqdm==4.67.1
trafilatura==2.0.0
transformers==4.47.1
triton==3.1.0
typer==0.15.1
typing_extensions==4.12.2
tzdata==2024.2
tzlocal==5.2
ujson==5.10.0
urllib3==2.3.0
uvicorn==0.22.0
uvloop==0.21.0
watchfiles==1.0.3
websockets==14.1
wikipedia==1.4.0
xxhash==1.4.4
yarl==1.18.3
zipp==3.21.0

```

**Comment by shaoyijia** [comment]
Thanks for letting me know!
