### ISSUE TITLE
Ollama support

### ISSUE THREAD

**Issue by Tamoghna12** [stanford-oval/storm#78]
Can you add ollama support to use it locally so that there is no dependence on openAI?

**Comment by myrulezzz** [comment]
python3.11 ./examples/run_storm_wiki_ollama.py 
Traceback (most recent call last):
  File "/Users/andreasstylianou/storm/./examples/run_storm_wiki_ollama.py", line 25, in <module>
    from lm import OllamaClient
ImportError: cannot import name 'OllamaClient' from 'lm' (/Users/andreasstylianou/storm/.venv/lib/python3.11/site-packages/lm/__init__.py)
i get this error when i try your example with ollama
