### ISSUE TITLE
Alternatives to You.com search API

### ISSUE THREAD

**Issue by songkq** [stanford-oval/storm#8]
@shaoyijia @Yucheng-Jiang Hi, I'm wondering if there are some other search APIs can be used for storm since that You.com API requires a credit card. 
https://github.com/stanford-oval/storm/blob/42f4d5bbbaca67bc2e4e8ea5814e0975fef971fc/src/modules/topic_expert.py#L79

For example, can these search APIs provided by langchain be used for alternatives to You.com.

- https://github.com/langchain-ai/langchain/blob/6dc4f592ba62fef08ba6bb832b7b6a4ef578f327/libs/community/langchain_community/utilities/duckduckgo_search.py#L11

- https://github.com/langchain-ai/langchain/blob/6dc4f592ba62fef08ba6bb832b7b6a4ef578f327/libs/community/langchain_community/utilities/bing_search.py#L13

- https://github.com/langchain-ai/langchain/blob/6dc4f592ba62fef08ba6bb832b7b6a4ef578f327/libs/community/langchain_community/utilities/brave_search.py#L9

- https://github.com/langchain-ai/langchain/blob/6dc4f592ba62fef08ba6bb832b7b6a4ef578f327/libs/community/langchain_community/utilities/tavily_search.py#L16

- https://github.com/langchain-ai/langchain/blob/6dc4f592ba62fef08ba6bb832b7b6a4ef578f327/libs/community/langchain_community/utilities/searx_search.py

- https://github.com/langchain-ai/langchain/blob/6dc4f592ba62fef08ba6bb832b7b6a4ef578f327/libs/community/langchain_community/utilities/searchapi.py#L9

**Comment by shaoyijia** [comment]
Hi, thanks for your interest!

We view this project as an example of a knowledge curation engine that serves as the intermediate layer between vase unstructured information and human. So, supporting different information sources is in our plan.

For the pointers you provide, are you willing to open a PR for integration? Happy to help merge it.

**Comment by songkq** [comment]
Yeah, I'll try to integrate more search APIs into storm.

**Comment by shaoyijia** [comment]
Great, thank you!

**Comment by LronDC** [comment]
If we have plans and a to-do list, I'd like to claim some tasks to help.

**Comment by Yucheng-Jiang** [comment]
@LronDC Thank you for your interest in our project! We're currently working on an upcoming code release that will enhance the scalability of the project. We will keep you updated and soon share some potential tasks where the community can contribute. Stay tuned!

**Comment by songkq** [comment]
@shaoyijia

**Comment by songkq** [comment]
@shaoyijia Considering supporting different information sources, I recommend you to use our open-source project, i.e., [QAnything](https://github.com/netease-youdao/QAnything). QAnything is a local knowledge base question-answering system designed to support a wide range of file formats and databases.

**Comment by dl942702882** [comment]
sadly, we cannot access to You.com。

**Comment by Yucheng-Jiang** [comment]
@dl942702882 You.com offers free tier of api quota. It’s sufficient to write more than 25 articles locally.

**Comment by shaoyijia** [comment]
@dl942702882 , for switching to customized sources (before we support this officially), maybe you can check out what this PR (#20) tries to do?

**Comment by shaoyijia** [comment]
An update in this thread:

We just release the refactored code to make it easier to run/customize/develop the STORM engine. Now, search API, retrieval model integration in [`src/rm.py`](https://github.com/stanford-oval/storm/blob/main/src/rm.py). The knowledge curation engine will directly consume the `Information` output by `Retriever`.

**Comment by shaoyijia** [comment]
@LronDC @songkq , we are now specifically interested in supporting:
1. Retrieval models that can retrieve information from customized source.
2. Search API that return academic sources, e.g., [Semantic Scholar API](https://www.semanticscholar.org/product/api)

Contribution is highly appreciated if you are interested!

**Comment by songkq** [comment]
@shaoyijia Hi, I'll support the [Semantic Scholar API](https://www.semanticscholar.org/product/api) soon after the API key is obtained.

**Comment by shaoyijia** [comment]
Hi @songkq , thank you so much! I have a Semantic Scholar API so can also test it.

**Comment by Yucheng-Jiang** [comment]
@songkq now we support with more retrieval methods, see documentation here: https://github.com/stanford-oval/storm?tab=readme-ov-file#api.

In addition to You.com, we also support Bing search, and customized corpus retrieval with vector database.
