### ISSUE TITLE
ModuleNotFoundError: No module named 'knowledge_storm'

### ISSUE THREAD

**Issue by sarkaramitabh300** [stanford-oval/storm#87]
when running this command, I am getting this issue.

python examples/run_storm_wiki_gpt.py \
    --output-dir $OUTPUT_DIR \
    --retriever you \
    --do-research \
    --do-generate-outline \
    --do-generate-article \
    --do-polish-article
Traceback (most recent call last):
  File "/Users/amitabhsarkar/Dev/Personal/AI/storm/examples/run_storm_wiki_gpt.py", line 25, in <module>
    from knowledge_storm import STORMWikiRunnerArguments, STORMWikiRunner, STORMWikiLMConfigs
ModuleNotFoundError: No module named 'knowledge_storm'

**Comment by bamit99** [comment]
Try pip install knowledge-storm

**Comment by pdatric** [comment]
I'm having the same error, all files were installed using the pip install knowledge-storm and verified

**Comment by ferrygun** [comment]
I added this line in the script:
import os
import sys
# Add the parent directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

**Comment by shawng00din** [comment]
> pip install knowledge-storm - Did the trick - I had to install like 3 other streamlit packages as well not sure why

**Comment by Yucheng-Jiang** [comment]
close the issue as resolved
