### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by tstanek390** [stanford-oval/storm#91]
Hello,
I guess its some trivial error on my side, but I cant get STORM working. 
python examples/run_storm_wiki_gpt.py \
    --output-dir /Users/admin/AI/storm \
    --update-vector-store \
    --retriever you \
    --do-research \
    --do-generate-outline \
    --do-generate-article \
    --do-polish-article
usage: run_storm_wiki_gpt.py [-h] [--output-dir OUTPUT_DIR] [--max-thread-num MAX_THREAD_NUM] [--retriever {bing,you}] [--do-research]
                             [--do-generate-outline] [--do-generate-article] [--do-polish-article] [--max-conv-turn MAX_CONV_TURN]
                             [--max-perspective MAX_PERSPECTIVE] [--search-top-k SEARCH_TOP_K] [--retrieve-top-k RETRIEVE_TOP_K]
                             [--remove-duplicate]
run_storm_wiki_gpt.py: error: unrecognized arguments: --update-vector-store

What Am I doing wrong?

P.S. when running it without  --update-vector-store  i get the same error which I had my previous Issue which was closed as solved, even when it wasnt solved.
Cheers

**Comment by shaoyijia** [comment]
@AMMAS1

**Comment by AMMAS1** [comment]
I think the file you are trying to run for custom data is run_storm_wiki_gpt_with_VectorRM.py. 

Right now you are running run_storm_wiki_gpt.py which doesn't work on custom data.

**Comment by tstanek390** [comment]
As i mentioned in another issue - with run_storm_wiki_gpt_with_VectorRM.py the STORM runs well, without any errors and produces decent results. I just wanted to run GUI streamlit version, and / or GPT / Claude instance. These are the options which i am unable to run :(

**Comment by Yucheng-Jiang** [comment]
close as duplicate issue of #62
