### ISSUE TITLE
[feature request]Adding serper.dev search to rm in python package

### ISSUE THREAD

**Issue by zenith110** [stanford-oval/storm#97]
Hi there!
Currently working in a company that utilizes storm, found this as an alternative for you.com.

https://serper.dev/

Will be taking a stab at the implementation, are there any contributing guidelines?

Thank you.

**Comment by shaoyijia** [comment]
Hi @zenith110 , thank you for taking a stab on this! Yes, we just create an initial [CONTRIBUTING.md](https://github.com/stanford-oval/storm/blob/main/CONTRIBUTING.md) to convey contributing guidelines. Thanks again for asking for it!

**Comment by zenith110** [comment]
Closing as #102  was merged in.
